import { getBooks } from "./bookAction";
import { Book_Type } from "./bookType";

const initialState={
    books:[
        {name:'The Complete Stories',author:'Flannery O\'Connor',review:'“A teacher gave me Flannery O’Connor’s short story collection in the ninth grade. I grew up in a small town where girls were taught to be polite and not laugh too loud or talk too much or show interest in anything that might scare away the boys. It was a revelation to read O’Connor’s work. Here was a woman from a small Georgia town (like me!) who in direct contravention to her sex and social class was writing the kinds of stories that I was not only interested in reading, but wanted to start writing myself. Her bravery and clarity of vision laid an early foundation for my own work.” —Karin Slaughter'},
        {name:'Letting Go',author:'Philip Roth',review:'“My dad gave me the novel Letting Go by Philip Roth. Dad read very little fiction—only one book of fiction a year. He was a political scientist, and he read dozens and dozens of non-fiction, academic books every year. But he always became enthusiastic about his one, annual book of fiction, which he would then recommend to everyone. He loved Roth. I like the novel, because it is Roth’s second—and unfamous—book; the writing shows his earnestness. He was looking for his voice then. I love the early novels of writers, for that same reason.” —Josh Barkan'},
        {name:'Fear of Flying',author:'Erica Jong',review:'“Knowing it is my favorite book, for my 34th birthday, a boyfriend once gave me a signed first edition of Erica Jong’s Fear of Flying.  Having always read tattered paperback versions, I had no idea the original was adorned with a spectacularly ornate cover that’s evocative of a Hieronymus Bosch.  I’m not a big collector of anything but no matter how often I pare down my belongings, I never get rid of this.  (Even though the boyfriend was long-ago lost to history, his accompanying birthday card remains tucked inside the book.)” —Lisa Napoli'},
        {name:'The French Laundry Cookbook',author:'Thomas Keller',review:'“In the winter of 2005, I received Thomas Keller’s The French Laundry Cookbook as a Christmas present.  It was during my early, struggling-writer years, when I was working as a chef to support my family (and my writing), and I often wondered if I’d ever make it as an author.  I remember sitting down on Christmas Day to read Keller’s book in my small apartment in Colorado.  I was inspired by his love for cooking, his artistry and creativity, and his deep dedication to his art.  The book was an inspiration to me to keep writing and pursuing my dream of publication, and I promised myself that when I published my first book, I would celebrate at one of his restaurants. Ten years later, I signed my contract for Children of the New World with Picador.  This past November, I invited my family to Per Se as a thank you for all their love and support throughout my years of writing, and I lifted a glass in thanks to Keller.” —Alexander Weinstein'},
        {name:'Wide Sargasso Sea',author:'Jean Rhys',review:'“My Mancunian grandmother, who left school at sixteen to work, was a very smart, insatiable reader. She was thrilled when I went to study English at university for three years, but still read far more than I did in that time. I remember thinking it might have been better, certainly cheaper, to enroll with her. She would mail me novels (always beautiful editions) and I would read the back, maybe a first line, and then pile them up beside my bed and feel guilty for not having the time amid weekly essays. My experience of ‘reading’ then could be more accurately described as ‘coloring.’ Extended procrastination followed by an intense period of highlighting, looking for key words and retaining nothing. Always in a post-midnight panic. Always, it felt like, incomprehensible lines of Chaucer. By the time it came to final exams, I’d read practically nothing post-1960 and so was pretty clueless in conversations about books other people had read.It wasn’t until after I finished my degree and my grandmother was very sick that I finally discovered the meaning of ‘reading for pleasure,’ and got round to chipping away at the books she’d sent, most of which I’d politely pretended to have enjoyed in my thank-you calls. I began with a beautiful blue Virago edition of Jean Rhys’ Wide Sargasso Sea, and was electrified. As Rhys’ Antoinette and Jane Eyre’s Bertha began to fuse in my mind, connecting an old favorite novel with a new one, the initial electrical jolt turned into a mixture of rage, wonder, and self-reproach for having put the experience off for so long. I realized I’d probably only told her I “liked” it on the phone. I rang her again, admitted the lie, and told her I wanted to write my own. She laughed and said ‘I knew it. Good. Get on with it.’” —Olivia Sudjic'},
        {name:'When Breath Becomes Air',author:'Paul Kalanithi',review:'“When Breath Becomes Air by Paul Kalanithi. Kalanithi’s brave memoir chronicles in exquisite prose his brave battle with terminal illness, but rather than verge into depressing territory, it is a triumphant and inspiring read.  His words make one rethink our perception of time—to not only imagine what we might achieve in the future, but to cherish the beauty that surrounds us in the present.” —Alyson Richman'},
        {name:'GENESIS',author:'Lélia Wanick Salgado',review:'“After our son Walker couch-surfed in Rio last year, we felt obliged to take in one of the Brazilian friends he met. She brought a copy of Sebastião Salgado’s beautiful but expensive book Genesis. We felt bad because she doesn’t have a lot of money and also because it is in Portuguese. However, 95% of the book consists of Salgado’s brilliant photographs, which need no translation. It seems that the people with the least often give the most.” —Robert Dawson'},
        {name:'The Manuscript Books of Emily Dickinson',author:'R. W. Franklin',review:'“Early in our marriage my husband gave me The Manuscript Books of Emily Dickinson, edited by R.W. Franklin and published by Harvard University Press. What an amazement to see her poems in her own hand, intact in their radical, astonished beauty without the many editorial interventions made after her death which silently “corrected” and altered her grammar, idiosyncratic capitalization, punctuation, and much else.  I could even see the alternate word-choices she left on the page—that feeling of the mind in motion.  Recently, New Directions published The Gorgeous Nothings, which beautifully reproduces her late envelope writings and includes as well a photo of the small pencil she carried in the pocket of her dress—another book to treasure.” —Laurie Sheck'},
        {name:'A Girl Like I',author:'Anita Loos',review:'“This book was given to me as a sort of joke gift by a friend, but it ended up serving two purposes: Firs, it’s a great read from one of the true female pioneers in the movie and theater world. Witty, smart, giving the reader a glimpse into an era that’s long gone. Second, the cover has enormous camp value, and always draws attention. So it works both intellectually and decoratively—not unlike some of the characters Loos wrote about!” —Robert Trachtenberg'},
        {name:'The Adventures of Tom Sawyer',author:'Mark Twain',review:'“On my eighth birthday my mother gave me a hardcover copy of The Adventures of Tom Sawyer. The inscription read: ‘Here is the brother you said you wanted.’ I was having trouble in school—particularly reading—and a psychologist had recently tested me and informed my mother and the school that I was, in the parlance of the day, ‘retarded.’ My mother steadfastly refused to accept this, saying, ‘You just haven’t found anything you care enough about to read.’ It turned out I was dyslexic and perhaps mildly autistic. It took me months, and when I was done, I could read, and I had indeed been given a brother—two, in fact, and I have visited with them every year since my eighth birthday.” —James Anderson'},
        {name:'In the Heart of the Sea',author:'Nathaniel Philbrick',review:'“Many years ago I was boarding a plane to Las Vegas, planning on doing two things I really enjoyed: gambling and reviewing All-You–Can-Eat buffets (I was young. Thankfully, I got both habits out of my system.). Also boarding was a large passenger sneezing and wheezing. Here was someone who desperately needed a bowl of chicken soup and a flight refund. While he squeezed his way down the aisle looking for his seat, everyone on the plane was thinking the same thing I was—I hope he doesn’t sit next to me. As he settled in next to me, I imagined the worst. Needless to say, by the end of the flight, we not only became friends who still keep in touch twenty years later, but he recommended a book which changed my life. During the flight, he sold me on In the Heart of the Sea by Nathaniel Philbrick. I asked my mom for this book for Christmas and as my Vegas friend promised, the book was extraordinary. So much so, it convinced me to write my own. Up until that point, I wrote comedy pieces and columns in publications but never anything long form. Speed up to today—20 years later—In the Heart of the Sea has been adapted into a movie and now that I’ve finished my current project (Footnotes from the World’s Greatest Bookstores), I plan to publish that illustrated novel inspired by my favorite book. Called The Sea Below Us, it’s a black comedy about the missing Sir John Franklin. I sent a manuscript to Nathaniel Philbrick—whom I have also met and kept in touch with over the years—and thanked him for the inspiration his book provided. He loved the manuscript.” —Bob Eckstein'},
        {name:'Little Women',author:'Louisa May Alcott',review:'“My grandmother was a complicated woman—angry, loving, gossipy, and vibrant. She lived a country’s length away from me, and we were never close, even though I was named after her. The truth is, her mercurial moods scared me a little. One Christmas morning when I was 10 or so, I unwrapped a heavy package and discovered a beautiful hardcover book complete with illustrations: Little Women. On the inside was my grandmother’s inscription in handwriting as bold as she was: For Sarah, with love. I devoured the book that day, then read it again and again. When I was immersed in its pages, I felt more connected to my grandmother than I ever had before; it was as if she truly saw me as the shy, book-loving girl I was, instead of the confident, outspoken one she perhaps wanted me to be. My grandmother died long ago, but I still have the worn, beloved copy of the novel she gave me, with her faded handwriting gracing the opening page. I cherish it still.” —Sarah Pekkanen'},
        {name:'Boy Wonder',author:'James Robert Baker',review:'“Back in high school, my best friend gave me a tattered paperback of Boy Wonder by the late/great James Robert Baker. We’d been into making movies, writing stories, and living imaginatively since kindergarten, and this gonzo, out-of-print novel about a young-madman-turned-Hollywood-super-producer had it all. Boy Wonder is the perfect summer read, a fount of crazed inspiration, laugh-out-loud funny, and to this day, one of the most seminal reading experiences I’ve had.” —Chris Sharp'},
        {name:'It',author:'Stephen King',review:'“The best book I ever received as a present was It by Stephen King for my 15th birthday. I was already a fan of Stephen King’s novels and had been anxiously awaiting the release of It. My step-dad had it wrapped and waiting for me the day it came out, with a hand-written note inside. The book was as amazing as I’d anticipated. But it’s the best book I’ve ever received because it marked the beginning of a tradition. Every birthday after that, my step-dad gave me a book. Some years it was Stephen King’s latest, some years it was another author. The tradition continued for a quarter century, until my step-dad passed away a few years ago. I still miss seeing a brightly wrapped book in amongst the other birthday gifts. And I still have that original, hard cover copy of It.” —Amy Engel'},
        {name:'The Phantom Tollbooth',author:'Norton Juster',review:'“In fifth grade, I received The Phantom Tollbooth by Norton Juster and spent the next three days wrapped up in the pages, unable to put it down. It was the first book that grabbed hold of me and didn’t let go. When I was a fifth grade teacher, I would read it aloud to my students every year and watch as the story of Milo and the mysterious Tollbooth grabbed them the way it grabbed me when I was that age. I still have that same weather-worn copy on my book shelf and look forward to the day I can hand it off to my son. —Katie Ganshert'}
        
    ]
}
const bookReducer=(state=initialState,action)=>{
    switch(action.type){
        case Book_Type:return{...state};break;
        default:return {...state};break;
    }
}

export default bookReducer;